Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname="control-node"
  config.vm.network "private_network",ip:"192.168.200.2"
  config.vm.synced_folder ".", "/vagrant"
 config.vm.provision "shell",path:"provision.sh"
 config.vm.boot_timeout = 1200
end
