Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname="app01"
  config.vm.network "private_network",ip:"192.168.200.3"
  config.vm.network "forwarded_port", guest:80,host:80
  config.vm.provision "shell",path:"provision.sh"
  config.vm.boot_timeout = 1200
end
